prompt_order = [
  "directory",
  "git_branch",
  "git_status",
  "aws",
  "line_break",
  "jobs",
  "character",
]

[directory]
fish_style_pwd_dir_length = 1

[git_branch]
symbol = ""

[aws]
symbol = ""
displayed_items = "profile"
